version: "3.8"
services:
  db:
    container_name: wanted-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: wanted
      MYSQL_USER: sol
      MYSQL_PASSWORD: sol123
      MYSQL_ROOT_PASSWORD: 0728
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    restart: always
    networks:
      - wanted_network

  app:
    build: .
    container_name: wanted-spring-boot
    environment:
      DB_URL: jdbc:mysql://db:3306/wanted?useSSL=false
      DB_USERNAME: sol
      DB_PASSWORD: sol123
      JWT_SECRET_KEY: aqq_wanted_preonBoarDing_wanted-application-2023.secret_key
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
    restart: always
    networks:
      - wanted_network

networks:
  wanted_network: